spring.datasource.url=jdbc:postgresql://172.22.1.47:36432/jamii
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
logging.level.org.springframework.web=INFO
logging.level.com.jamii.explorer=DEBUG
jamii.jsonrpc.url=http://localhost:8545
