data_dir: "./"
node_key_file: "./nodekey"
miner_enabled: true
rpc_port: 8548
p2p_port: 30306
static_peers:
  - "node_a:30303"
  - "node_b:30304"
  - "node_c:30305"
  - "node_e:30307"
  - "archiver:30310"  
log_level: "error"
genesis_file: "./genesis.json"
torrent_port: 42003
torrent_peers:
  - "node_a:42000"
  - "node_b:42001"
  - "node_c:42002"
  - "node_e:42004"
