data_dir: "./"
node_key_file: "./nodekey"
miner_enabled: true
rpc_port: 8546
p2p_port: 30304
static_peers:
  - "node_a:30303"
  - "node_c:30305"
  - "node_d:30306"
  - "node_e:30307"
  - "archiver:30310"  
log_level: "info"
genesis_file: "./genesis.json"
torrent_port: 42001
torrent_peers:
  - "node_a:42000"
  - "node_c:42002"
  - "node_d:42003"
  - "archiver:42020"
